### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by ctucker0113** [nss-evening-cohort-24/pos-system-a-pizza-my-heart#5]

**Comment by Lucas-Martin2023** [comment]
# User Story
The User should see the navbar once they login. They should see this on every page after the login and should disappear after the user logs out. The user should see the logo of the restaurant, View Orders, Create an Order, Search Orders, and Logout button. 

# Dev Notes
This is dependent on the user logging in.
View Orders should be a button.
Create an Order should be a button.
Search Orders should be a field that a user can input text.
Logout Button should be on the far right of the navbar.

**Comment by ctucker0113** [comment]
# User Story

On every page after logging in, a user should see a Navbar at the top of the page which allows them to navigate to the home page, the View Orders page, or logout from the app altogether.

# Dependencies
Proper functioning of the navbar will be contingent on the functions required to make the individual buttons usable (i.e. - the pages that the buttons are supposed to take the user to will need to be completed for the navbar links to work.)

# Dev Notes
Promises in API Code:

getOrders > method: 'GET'
![Screenshot 2023-09-17 at 1 04 33 PM](https://github.com/nss-evening-cohort-24/pos-system-a-pizza-my-heart/assets/134985404/fc26f4a4-2de4-43bc-a840-c1240326b729)

Functions to code:

- [ ] showOrdersPage
- [ ] showCreateOrderPage
- [ ] clearDom
- [ ] showEmptyOrdersPage
- [ ] getOrders
- [ ] searchOrders

When the user clicks the "View Orders" button, the event listener will run "getOrders.then showOrders" function with the parameter of user.uid.

Example code for the event listener:
![Screenshot 2023-09-17 at 12 35 19 PM](https://github.com/nss-evening-cohort-24/pos-system-a-pizza-my-heart/assets/134985404/b8cd9440-176e-45a7-a0cd-ddd28c330763)


When the user clicks the "Create Orders" button, the event listener will trigger the showCreateOrdersPage function.
Example code for event listener:
![Screenshot 2023-09-17 at 12 41 57 PM](https://github.com/nss-evening-cohort-24/pos-system-a-pizza-my-heart/assets/134985404/a2f7d083-489f-4bc5-944e-94fe2dc59b6d)


# Acceptance Criteria
This part of the project can be considered complete when:
- [ ] The "View Orders" "Create an Order" and "View Revenue" buttons are functional
- [ ] The Navbar is properly rendered at the top of the screen
