### ISSUE TITLE
Create Home Screen

### ISSUE THREAD

**Issue by ctucker0113** [nss-evening-cohort-24/pos-system-a-pizza-my-heart#6]

**Comment by dipolarbear25** [comment]
# User Story
when logging into the home screen, users should be greeted with a "welcome (user)!", and the view orders, create an order, and view revenue buttons. the nav bar should also pop up with the logo, view orders, create orders, logout and a search bar function.
# Dev Notes
nav bar must be finished with functionality along with the buttons.
home page needs to display users name
logo needs to be displayed

**Comment by ctucker0113** [comment]
# User Story
When logging into the website, the home screen will display "Welcome (user's name)!". Then 3 buttons under the welcome that say "view orders" "create an order" and "view revenue". A nav bar should be at the top of the screen with 3 buttons, a logo, and a search bar, the buttons will be "view orders" "create an order" and "logout"

# Dependencies
This page is dependent on the login auth (login page) and the postman calls being properly tested in firebase.

# Dev Notes
Promises in API Code:

getOrders > method: 'GET'

Functions to code: 

- [ ] showOrdersPage
- [ ] showCreateOrderPage
- [ ] clearDom
- [ ] showEmptyOrdersPage
- [ ] showRevenuePage
- [ ] getOrders

When the user clicks the "View Orders" button, the event listener will run "getOrders.then showOrders" function with the parameter of user.uid. 

Example code for the event listener:
![Screenshot 2023-09-17 at 12 35 19 PM](https://github.com/nss-evening-cohort-24/pos-system-a-pizza-my-heart/assets/134985404/1afe77f3-1a1f-4f66-9ad3-23e0a55d98cb)

When the user clicks the "Create Orders" button, the event listener will trigger the showCreateOrdersPage function.
Example code for event listener:
![Screenshot 2023-09-17 at 12 41 57 PM](https://github.com/nss-evening-cohort-24/pos-system-a-pizza-my-heart/assets/134985404/6acf44f3-b514-4560-b7ab-36ef5bfff46b)


# Acceptance Criteria
This section can be considered complete when the following things occur on the page:

- [ ] The page renders the user's name
- [ ] The "View Orders" "Create an Order" and "View Revenue" buttons are functional
- [ ] The Navbar is properly rendered at the top of the screen
